import '@radix-ui/themes/styles.css'
import './theme-config.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto_Mono } from 'next/font/google'
import { Theme } from '@radix-ui/themes'
import NavBar from '@/app/NavBar'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${roboto_mono.className}`}>
        <Theme accentColor='violet'>
          <NavBar />
          <main className='p-5'>{children}</main>
          {/*<ThemePanel />*/}
        </Theme>
      </body>
    </html>
  )
}
