import '@radix-ui/themes/styles.css'
import './theme-config.css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto_Mono } from 'next/font/google'
import { Container, Theme } from '@radix-ui/themes'
import NavBar from '@/app/NavBar'
import AuthProvider from '@/app/auth/Provider'

const inter = Inter({
  subsets: ['latin'],
  // variable: '--font-inter',
  // preload: false,
})

// const roboto_mono = Roboto_Mono({
//   subsets: ['latin'],
//   display: 'swap',
//   preload: true,
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider>
          <Theme accentColor='violet'>
            <NavBar />
            <main className='p-5'>
              <Container>{children}</Container>
            </main>
            {/*<ThemePanel />*/}
          </Theme>
        </AuthProvider>
      </body>
    </html>
  )
}
